### ISSUE TITLE
Resolve Memory Leak

### ISSUE THREAD

**Issue by thinq4yourself** [BeardandFedora/WriteOn#24]
We have a pretty serious memory leak in WriteOn. Here are the options:
1. Increase dynos until resolved (**ideal**)
2. Install log-runtime-metrics for analysis (done)
3. [Analyze results](https://devcenter.heroku.com/articles/log-runtime-metrics#log-format) in Papertrail
4. Re-install Nodetime and [analyze](http://blog.nodetime.com/2012/07/detecting-memory-leaks-in-nodejs-apps.html) (done)

![screenshot 2015-04-29 at 20 20 44](https://cloud.githubusercontent.com/assets/147231/7404174/4cb9ab1c-eead-11e4-9e98-ed86fbe40fdc.png)

**Comment by thinq4yourself** [comment]
Bumping @yaboi as an FYI

**Comment by yaboi** [comment]
Let's hold off on Dynos until it affects users. If that's the case, by all means, let's bump up dynos until fixed.

**Comment by thinq4yourself** [comment]
Okie dokie, this is currently resolved in version 1.8.1 in production, but needs rework to be automated for scalability. This was solved by turning off clustering for now, but by implementing enhancement #28 we will in turn revert back to clustering with concurrency and have an infinitely scalable solution optimized for Heroku.
