### ISSUE TITLE
Navbar Responsiveness needs imrpoving

### ISSUE THREAD

**Issue by thinq4yourself** [BeardandFedora/WriteOn#27]
The navbar needs consolidating to ensure proper responsive degradation for smaller screens, primarily tablets.

This includes which menus, items and navbars get hidden at which screen size. 

Most of this work can be done in the html, layout.js, and some css magic.

**Comment by thinq4yourself** [comment]
Done in v1.9.10

**Comment by yaboi** [comment]
W00t - Mobile friendly!

I hear a blog post topic... "WriteOn is now fully mobile friendly!"
